### ISSUE TITLE
Segfault when removing script

### ISSUE THREAD

**Issue by mgerhardy** [SpookyGhost2D/SpookyGhost#4]
Played the ghost circle animation and added a random second lua script to it. Then I tried to delete the circle script => Segfault.

**Comment by encelo** [comment]
Hello @mgerhardy and thank you for your report.

I have tried to add a second script to both `scripted_rotations.lua` and `scripted_rotations_staggered.lua` and then remove `circle.lua` but I cannot reproduce the crash.

Can you tell me on which platform did you do the test and the program version from the about window?
